DROP PROCEDURE IF EXISTS TEST_PROCEDURE_VERBOSE;
DELIMITER //
CREATE PROCEDURE TEST_PROCEDURE_VERBOSE(procedure_name VARCHAR(255))
BEGIN
   CALL TESt_PROCEDURE_BY_ASSERT(procedure_name, 1, '');
END//
DELIMITER ;