DROP PROCEDURE IF EXISTS TEST_FUNCTION_VERBOSE;
DELIMITER //
CREATE PROCEDURE TEST_FUNCTION_VERBOSE(function_name VARCHAR(255))
BEGIN
   CALL TEST_FUNCTION_BY_ASSERT(function_name, 1, '');
END//
DELIMITER ;