-- Get DDL comment for TABLE `unit_name` in database `unit_db`

DROP FUNCTION IF EXISTS GET_TABLE_COMMENT;
DELIMITER //
CREATE FUNCTION GET_TABLE_COMMENT(unit_db VARCHAR(255), unit_name VARCHAR(255))
RETURNS VARCHAR(255)
BEGIN
   RETURN GET_TABLE_FIELD(unit_db, unit_name, 'TABLE_COMMENT');
END//
DELIMITER ;
