-- Get error trace for register session variable (State 80600)
DROP PROCEDURE IF EXISTS GET_FAILURE_FOR_REGISTER_VARIABLE;
DELIMITER //
CREATE PROCEDURE GET_FAILURE_FOR_REGISTER_VARIABLE(
   var_name VARCHAR(255),
   d INT
)
BEGIN
   DECLARE message VARCHAR(255) DEFAULT '';
   IF d THEN
      CALL GET_TRACE_FOR_REGISTER_VARIABLE(var_name);          
   END IF;
   SET message = GET_ERROR_FOR_REGISTER_VARIABLE();
   SIGNAL SQLSTATE '80600' SET MESSAGE_TEXT = message;
END//
DELIMITER ;