-- Register session variables for PROCEDURE testing

DROP PROCEDURE IF EXISTS REGISTER_PROCEDURE_VARIABLES;
DELIMITER //
CREATE PROCEDURE REGISTER_PROCEDURE_VARIABLES()
BEGIN
   CALL REGISTER_VARIABLES('PROCEDURE');
END//
DELIMITER ;