-- Register session variables for FUNCTION testing

DROP PROCEDURE IF EXISTS REGISTER_FUNCTION_VARIABLES;
DELIMITER //
CREATE PROCEDURE REGISTER_FUNCTION_VARIABLES()
BEGIN
   CALL REGISTER_VARIABLES('FUNCTION');
END//
DELIMITER ;