-- Release session variables for PROCEDURE testing

DROP PROCEDURE IF EXISTS RELEASE_PROCEDURE_VARIABLES;
DELIMITER //
CREATE PROCEDURE RELEASE_PROCEDURE_VARIABLES()
BEGIN
   CALL RELEASE_VARIABLES('PROCEDURE');
END//
DELIMITER ;