-- Release session variables for FUNCTION testing

DROP PROCEDURE IF EXISTS RELEASE_FUNCTION_VARIABLES;
DELIMITER //
CREATE PROCEDURE RELEASE_FUNCTION_VARIABLES()
BEGIN
   CALL RELEASE_VARIABLES('FUNCTION');
END//
DELIMITER ;